"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, Check, ShieldCheck, Sparkles } from "lucide-react";

export function AuthPage({ mode, signedIn }: { mode: "login" | "register"; signedIn: boolean }) {
  const register = mode === "register";
  const signInPath = "/signin-with-chatgpt?return_to=%2Fdashboard";
  return <main className="auth-canvas min-h-screen overflow-hidden bg-[#07101f] text-white">
    <div className="auth-orb auth-orb-one" /><div className="auth-orb auth-orb-two" />
    <header className="relative z-10 mx-auto flex max-w-[1180px] items-center justify-between px-6 py-6"><Link href="/" className="group flex items-center gap-3"><span className="relative grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-white text-[#07101f]"><span className="relative z-10 font-mono text-sm font-black">L</span><span className="absolute -right-2 -top-2 h-5 w-5 rounded-full bg-[#b8ed3a] transition-transform duration-500 group-hover:scale-150" /></span><span><strong className="block text-sm tracking-[.15em]">LUMEN</strong><span className="text-[9px] uppercase tracking-[.2em] text-white/45">Decision intelligence</span></span></Link><Link href="/" className="rounded-full border border-white/10 px-4 py-2 text-xs text-white/65 transition-all duration-300 hover:border-white/30 hover:text-white">Back to home</Link></header>
    <section className="relative z-10 mx-auto grid min-h-[calc(100vh-92px)] max-w-[1180px] items-center gap-12 px-6 pb-14 lg:grid-cols-[1fr_460px]">
      <div className="auth-copy hidden lg:block"><span className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#b8ed3a]/20 bg-[#b8ed3a]/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-[#b8ed3a]"><Sparkles className="h-3.5 w-3.5" /> Intelligence at decision speed</span><h1 className="max-w-xl text-6xl font-semibold leading-[.96] tracking-[-.065em]">Your data already knows what comes next.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/55">Lumen turns spreadsheets and reports into clear signals, defensible decisions, and board-ready narratives.</p><div className="mt-10 grid max-w-lg grid-cols-3 gap-3">{[{ value: "20 sec", label: "to first insight" }, { value: "14+", label: "chart types" }, { value: "3", label: "AI providers" }].map((item) => <div key={item.label} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 backdrop-blur"><strong className="block text-xl text-[#b8ed3a]">{item.value}</strong><span className="mt-1 block text-[10px] uppercase tracking-wider text-white/40">{item.label}</span></div>)}</div></div>
      <div className="auth-card relative rounded-[28px] border border-white/10 bg-[#0d1829]/85 p-7 shadow-2xl shadow-black/40 backdrop-blur-2xl sm:p-9"><span className="mb-7 grid h-11 w-11 place-items-center rounded-2xl bg-[#2764ff] shadow-lg shadow-[#2764ff]/30">{register ? <Sparkles className="h-5 w-5" /> : <ShieldCheck className="h-5 w-5" />}</span><h2 className="text-3xl font-semibold tracking-[-.045em]">{signedIn ? "Welcome back" : register ? "Create your workspace" : "Sign in to Lumen"}</h2><p className="mt-2 text-sm leading-6 text-white/50">{signedIn ? "Your secure session is ready." : register ? "Start analyzing with a secure ChatGPT identity. No new password to remember." : "Continue with the identity already secured by your ChatGPT account."}</p>
        <a href={signedIn ? "/dashboard" : signInPath} className="group mt-8 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-white font-semibold text-[#07101f] transition-all duration-300 hover:-translate-y-0.5 hover:bg-[#b8ed3a] hover:shadow-xl hover:shadow-[#b8ed3a]/15">{signedIn ? "Open your dashboard" : register ? "Create account with ChatGPT" : "Continue with ChatGPT"}<ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" /></a>
        <div className="my-7 flex items-center gap-3"><span className="h-px flex-1 bg-white/10" /><span className="text-[10px] uppercase tracking-[.16em] text-white/25">Secure access</span><span className="h-px flex-1 bg-white/10" /></div>
        <ul className="space-y-3">{["Passwords are never stored by Lumen", "Your datasets stay on your device", "Provider keys remain in your browser"].map((item) => <li key={item} className="flex items-center gap-3 text-xs text-white/55"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#b8ed3a]/15 text-[#b8ed3a]"><Check className="h-3 w-3" /></span>{item}</li>)}</ul>
        <p className="mt-7 text-center text-xs text-white/35">{register ? "Already have access?" : "New to Lumen?"} <Link href={register ? "/login" : "/register"} className="font-semibold text-white transition-colors hover:text-[#b8ed3a]">{register ? "Sign in" : "Create an account"}</Link></p>
      </div>
    </section>
  </main>;
}
